/*
    app.js
    code for our demo application
 */

"use strict";

//this is the base URL for all task objects managed by your application
//requesting this with a GET will get all tasks objects
//sending a POST to this will insert a new task object
//sending a PUT to this URL + '/' + task.objectId will update an existing task
//sending a DELETE to this URL + '/' + task.objectId will delete an existing task
var tasksUrl = 'https://api.parse.com/1/classes/tasks';

angular.module('ToDoApp', ['ui.bootstrap'])
    .config(function($httpProvider) {
        //Parse required two extra headers sent with every HTTP request: X-Parse-Application-Id, X-Parse-REST-API-Key
        //the first needs to be set to your application's ID value
        //the second needs to be set to your application's REST API key
        //both of these are generated by Parse when you create your application via their web site
        //the following lines will add these as default headers so that they are sent with every
        //HTTP request we make in this application
        $httpProvider.defaults.headers.common['X-Parse-Application-Id'] = 'ugCwnnqo65qcyIRaARlqy1pbieHTtTLkCPpFrxEz';
        $httpProvider.defaults.headers.common['X-Parse-REST-API-Key'] = 'LHWiWtpBUlGPGgC4CvK5sdqNjouVT35juBFWeJpv';
    })

    // Build a new controller
    .controller('TasksController', function($scope, $http) {

        // Initialize a New Task object
        $scope.newTask = {done: false};


        $scope.refreshTasks = function() {
            $scope.loading = true;
            $http.get(tasksUrl + '?where={"done": false}')
                .success(function(data) {
                    $scope.tasks = data.results;
                })
                .error(function(err) {
                    $cope.errorMessage = err;
                })
                .finally(function() {
                   $scope.loading = false;
                });
        };

        // Refresh upon load
        $scope.refreshTasks();

        // Adds a task to the list
        $scope.addTask = function() {

            $http.post(tasksUrl, $scope.newTask)
                .success(function(responseData) {
                    $scope.newTask.objectId = responseData.objectId;
                    $scope.tasks.push($scope.newTask);
                    $scope.newTask = {done: false};
                })
                .error(function(err) {
                    $scope.errorMessage = err;
                })
                .finally(function() {
                    // Nothing for finally
                });
        };

        // Updates a task
        $scope.updateTask = function(task) {
            $scope.loading = true;
          $http.put(tasksUrl + '/' + task.objectId, task)
              .success(function() {
                // Don't need to to much upon a success
              })
              .error(function() {
                  $scope.errorMessage = err;
              })
              .finally(function() {
                  $scope.loading = false;
              });
        };


        // Changes a vote
        $scope.changeVote = function(task, amount) {
            $scope.loading = true;
            $http.put(tasksUrl + '/' + task.objectId, {
                votes: {
                    __op: 'Increment',
                    amount: amount
                }
            })
                .success(function(responseData) {
                    task.votes = responseData.votes;
                })
                .error(function(err) {
                    $scope.errorMessage = err;
                })
                .finally(function() {
                   $scope.loading = false;
                });

        };
    });
